name: thirumathikart_app
description: A Flutter App for thirumathikartE+.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.3.8
  get_storage:
  smooth_page_indicator: 1.0.0+2
  font_awesome_flutter: 10.1.0
  lottie: ^1.3.0
  google_fonts: ^2.1.0 
  carousel_slider: ^4.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/banner/
